# Generated by Django 3.2.18 on 2023-04-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meta',
        ),
    ]
