# Generated by Django 3.2.18 on 2023-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_delete_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingred',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
