# Generated by Django 3.2.18 on 2023-04-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0003_recipe_recipe_ingred'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default=1, upload_to='photo/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='puplished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(choices=[('dessert', 'dessert'), ('chicken', 'Chicken'), ('meat', 'Meat'), ('drinks', 'drinks')], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_step',
            field=models.TextField(default=1, max_length=2000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('puplished', 'puplished'), ('draft', 'draft')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingred',
            field=models.TextField(null=True),
        ),
    ]
