# Generated by Django 3.2.18 on 2023-05-03 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_recipe_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.catagory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(upload_to='photo/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_step',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('puplished', 'puplished'), ('draft', 'draft')], max_length=20),
        ),
    ]
