# Generated by Django 3.2.18 on 2023-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20230503_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default=1, upload_to='photo/%y/%m/%d'),
        ),
    ]
