# Generated by Django 3.2.18 on 2023-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(upload_to='photo/%y/%m/%d'),
        ),
    ]
